baseurl: /sanluisobispo
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: sanluisobispo
github_org: maptime
maptime:
  chapter: MaptimeSLO
  #twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
